const venues = [
  {name:"Aloha Beer Kakaʻako", neighborhood:"Kakaako", area:"Kakaʻako", days:"Daily", early:"2:00–6:00 PM", late:"—", beer:null, drinks:"$2 off draft pints", food:"$15-and-under happy-hour food menu", tags:["brewery","food"], source:"https://alohabeer.com/pages/locations", slots:{0:[[14,18]],1:[[14,18]],2:[[14,18]],3:[[14,18]],4:[[14,18]],5:[[14,18]],6:[[14,18]]}},
  {name:"Moku Kitchen", neighborhood:"Kakaako", area:"Kakaʻako", days:"Daily", early:"2:00–5:30 PM", late:"Late-night varies", beer:null, drinks:"Discounted drinks", food:"50% off small plates; $12 pizzas reported", tags:["food","groups"], source:"https://honolulutravels.com/honolulu-happy-hour-guide/", slots:{0:[[14,17.5]],1:[[14,17.5]],2:[[14,17.5]],3:[[14,17.5]],4:[[14,17.5]],5:[[14,17.5]],6:[[14,17.5]]}},
  {name:"PITCH Sports Bar", neighborhood:"Kakaako", area:"Kakaʻako", days:"Daily", early:"2:30–6:30 PM", late:"—", beer:null, drinks:"Beer bucket specials reported", food:"$3 hand rolls reported", tags:["sports","sushi"], source:"https://pitchsportsbar.com/about", slots:{0:[[14.5,18.5]],1:[[14.5,18.5]],2:[[14.5,18.5]],3:[[14.5,18.5]],4:[[14.5,18.5]],5:[[14.5,18.5]],6:[[14.5,18.5]]}},
  {name:"Bevy", neighborhood:"Kakaako", area:"Kakaʻako", days:"Tue all night; Wed–Sat", early:"5:00–7:00 PM Wed–Sat", late:"All night Tue", beer:5, drinks:"$5 Corona / Modelo / Kirin", food:"Seasonal / pop-up food", tags:["cocktails","late"], source:"https://bevyhawaii.com/happy-hour/", slots:{2:[[17,24]],3:[[17,19]],4:[[17,19]],5:[[17,19]],6:[[17,19]]}},
  {name:"Hana Koa Brewing Co.", neighborhood:"Kakaako", area:"Kakaʻako", days:"Tue–Fri", early:"3:00–6:00 PM", late:"—", beer:null, drinks:"Brewery happy-hour specials", food:"Happy-hour menu available", tags:["brewery"], source:"https://www.hanakoabrewing.com/", slots:{2:[[15,18]],3:[[15,18]],4:[[15,18]],5:[[15,18]]}},
  {name:"The Row Kakaʻako", neighborhood:"Kakaako", area:"Kakaʻako", days:"Daily", early:"Daily specials — confirm hours", late:"—", beer:4, drinks:"$4 High Life / Coors Banquet; $4 wells", food:"—", tags:["cheap"], source:"https://www.therowkakaako.bar/menu", slots:{}},
  {name:"ELEVEN", neighborhood:"Ala Moana", area:"Ala Moana", days:"Wed–Sun", early:"Open–6:30 PM", late:"—", beer:null, drinks:"Discounted classic cocktails", food:"$2 oysters reported", tags:["oysters","date"], source:"https://www.elevenhnl.com/", slots:{}},
  {name:"Mai Tai’s Ala Moana", neighborhood:"Ala Moana", area:"Ala Moana", days:"Daily", early:"3:00–7:00 PM", late:"8:00–11:00 PM Sun–Thu", beer:5, drinks:"$5 domestic beers", food:"1/2 off pupus", tags:["music","late","food"], source:"https://www.maitaishawaii.com/happy-hour/", slots:{0:[[15,19],[20,23]],1:[[15,19],[20,23]],2:[[15,19],[20,23]],3:[[15,19],[20,23]],4:[[15,19],[20,23]],5:[[15,19]],6:[[15,19]]}},
  {name:"Lucky Strike Honolulu", neighborhood:"Ala Moana", area:"Ala Moana", days:"Mon–Fri", early:"1:00–5:00 PM", late:"—", beer:6, drinks:"$6 drafts / wells / house wine", food:"Select $6 food items", tags:["games","groups"], source:"https://www.bowlero.com/", slots:{1:[[13,17]],2:[[13,17]],3:[[13,17]],4:[[13,17]],5:[[13,17]]}},
  {name:"Morton’s The Steakhouse", neighborhood:"Ala Moana", area:"Ala Moana", days:"Sun–Fri", early:"4:00–6:30 PM", late:"—", beer:null, drinks:"Power Hour bar specials", food:"Steakhouse bar bites", tags:["upscale","date"], source:"https://www.mortons.com/", slots:{0:[[16,18.5]],1:[[16,18.5]],2:[[16,18.5]],3:[[16,18.5]],4:[[16,18.5]],5:[[16,18.5]]}},
  {name:"Doraku Sushi Kakaʻako", neighborhood:"Ala Moana", area:"Kapiʻolani / Ala Moana", days:"Mon–Fri", early:"4:00–6:00 PM", late:"9:00 PM–close", beer:null, drinks:"Happy-hour drinks", food:"Sushi / izakaya specials", tags:["sushi","late"], source:"https://dorakusushi.com/kakaako/menu/drink", slots:{1:[[16,18],[21,24]],2:[[16,18],[21,24]],3:[[16,18],[21,24]],4:[[16,18],[21,24]],5:[[16,18],[21,24]]}},
  {name:"DECK. Waikiki", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"Drinks 2:00–6:00 PM", late:"—", beer:6, drinks:"$6 bottles/cans; $8 local drafts", food:"Fries $6; sliders $15; other plates", tags:["view","food"], source:"https://www.deckwaikiki.com/qr/", slots:{0:[[14,18]],1:[[14,18]],2:[[14,18]],3:[[14,18]],4:[[14,18]],5:[[14,18]],6:[[14,18]]}},
  {name:"Lost + Found at Wayfinder", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"2:00–5:00 PM", late:"—", beer:5, drinks:"$5 draft beers", food:"—", tags:["poolside","cheap"], source:"https://www.wayfinderwaikiki.com/eat-drink/lost-found/", slots:{0:[[14,17]],1:[[14,17]],2:[[14,17]],3:[[14,17]],4:[[14,17]],5:[[14,17]],6:[[14,17]]}},
  {name:"The Seaside", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"Open–6:00 PM", late:"—", beer:4, drinks:"$4 Heineken / Kirin Light / Corona", food:"Oysters / seafood happy-hour menu", tags:["seafood","cheap"], source:"https://www.seasidewaikiki.com/menu/happy-hour", slots:{}},
  {name:"The Butcher Bar", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"4:00–6:00 PM", late:"—", beer:6, drinks:"$6 happy-hour draft", food:"$5 jerky; $7 fries; $25 butcher’s cut", tags:["steak","food"], source:"https://www.thebutcherbarwaikiki.com/happyhour", slots:{0:[[16,18]],1:[[16,18]],2:[[16,18]],3:[[16,18]],4:[[16,18]],5:[[16,18]],6:[[16,18]]}},
  {name:"SKY Waikiki", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"4:00–6:00 PM", late:"—", beer:5, drinks:"$5 Modelo; $10 bubbly", food:"$4 oysters", tags:["rooftop","view","oysters"], source:"https://skywaikiki.com/", slots:{0:[[16,18]],1:[[16,18]],2:[[16,18]],3:[[16,18]],4:[[16,18]],5:[[16,18]],6:[[16,18]]}},
  {name:"Earls Kitchen + Bar Waikiki", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"2:00–5:00 PM", late:"10:00 PM–close daily", beer:null, drinks:"Many cocktails 1/2 price; $3 off beer/wine", food:"$10 fish taco; $17 steak frites", tags:["late","food"], source:"https://earls.ca/locations/earls-waikiki/menu", slots:{0:[[14,17],[22,24]],1:[[14,17],[22,24]],2:[[14,17],[22,24]],3:[[14,17],[22,24]],4:[[14,17],[22,24]],5:[[14,17],[22,24]],6:[[14,17],[22,24]]}},
  {name:"Chart House Waikiki", neighborhood:"Waikiki", area:"Waikīkī / Harbor", days:"Daily", early:"3:30–6:00 PM", late:"9:00–10:30 PM", beer:6, drinks:"$6 domestic bottles / wells; $7 drafts", food:"$10 and $13 pupus", tags:["late","harbor"], source:"https://charthousewaikiki.com/menus/happy-hour-waikiki-menu/", slots:{0:[[15.5,18],[21,22.5]],1:[[15.5,18],[21,22.5]],2:[[15.5,18],[21,22.5]],3:[[15.5,18],[21,22.5]],4:[[15.5,18],[21,22.5]],5:[[15.5,18],[21,22.5]],6:[[15.5,18],[21,22.5]]}},
  {name:"Tommy Bahama Restaurant & Bar", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"3:00–5:00 PM", late:"—", beer:8, drinks:"$8 select draft beer; $10 wells", food:"All starters $5 off; sliders/tacos deals", tags:["rooftop","relaxed"], source:"https://content.tommybahama.com/content/dam/tommy/restaurants/waikiki/Waikiki_Dinner_Menu.pdf", slots:{0:[[15,17]],1:[[15,17]],2:[[15,17]],3:[[15,17]],4:[[15,17]],5:[[15,17]],6:[[15,17]]}},
  {name:"Hy’s Steak House", neighborhood:"Waikiki", area:"Waikīkī", days:"Nightly", early:"5:00–6:30 PM", late:"—", beer:null, drinks:"Happy-hour cocktails / wine", food:"Oysters, shrimp cocktail & bar bites", tags:["upscale","date"], source:"https://hyswaikiki.com/happy-hour/", slots:{0:[[17,18.5]],1:[[17,18.5]],2:[[17,18.5]],3:[[17,18.5]],4:[[17,18.5]],5:[[17,18.5]],6:[[17,18.5]]}},
  {name:"Splash Bar Waikiki", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"3:00–5:00 PM", late:"—", beer:null, drinks:"$2 off draft beers; $12 cocktails", food:"$7 fries / dip / edamame", tags:["casual","hotel"], source:"https://www.splashbarwaikiki.com/specials", slots:{0:[[15,17]],1:[[15,17]],2:[[15,17]],3:[[15,17]],4:[[15,17]],5:[[15,17]],6:[[15,17]]}},
  {name:"Aloha Table Waikiki", neighborhood:"Waikiki", area:"Waikīkī", days:"Daily", early:"Confirm current hours", late:"—", beer:5, drinks:"$5 Bud Light; $6.50 Aloha Blonde", food:"Under-$10 dishes", tags:["cheap","casual"], source:"https://www.waikiki.alohatable.com/happy-hour", slots:{}},

  {name:"808 Craft House", neighborhood:"West Oahu", area:"Ko Olina", days:"Daily", early:"3:00–5:00 PM", late:"9:00 PM–close", beer:7, drinks:"$7 select drafts; $7 wells; $9 Mai Tais", food:"25% off select apps; $15 smashburger", tags:["late","food","resort"], source:"https://www.808craft.com/happy-hour/", slots:{0:[[15,17],[21,23]],1:[[15,17],[21,23]],2:[[15,17],[21,23]],3:[[15,17],[21,23]],4:[[15,17],[21,23]],5:[[15,17],[21,23]],6:[[15,17],[21,23]]}},
  {name:"Monkeypod Kitchen Ko Olina", neighborhood:"West Oahu", area:"Ko Olina", days:"Daily", early:"3:30–5:00 PM", late:"—", beer:null, drinks:"Happy-hour craft beer & cocktail specials", food:"Selected happy-hour food", tags:["food","resort","music"], source:"https://koolinashops.com/dining/monkeypod-kitchen-by-merriman", slots:{0:[[15.5,17]],1:[[15.5,17]],2:[[15.5,17]],3:[[15.5,17]],4:[[15.5,17]],5:[[15.5,17]],6:[[15.5,17]]}},
  {name:"Mekiko Cantina", neighborhood:"West Oahu", area:"Ko Olina", days:"Daily", early:"3:00–5:00 PM", late:"—", beer:null, drinks:"Select drink & cocktail specials", food:"Happy-hour appetizers", tags:["mexican","resort","food"], source:"https://koolinashops.com/offers", slots:{0:[[15,17]],1:[[15,17]],2:[[15,17]],3:[[15,17]],4:[[15,17]],5:[[15,17]],6:[[15,17]]}},
  {name:"Moani Island Bistro & Bar", neighborhood:"West Oahu", area:"Kapolei", days:"Daily", early:"3:00–5:00 PM", late:"—", beer:null, drinks:"Daily happy-hour drink specials", food:"Happy-hour food menu", tags:["music","food","local"], source:"https://www.moanikapolei.com/", slots:{0:[[15,17]],1:[[15,17]],2:[[15,17]],3:[[15,17]],4:[[15,17]],5:[[15,17]],6:[[15,17]]}},
  {name:"Maui Brewing Co. Kailua", neighborhood:"Windward", area:"Kailua", days:"Mon–Fri", early:"3:30–5:30 PM", late:"—", beer:null, drinks:"$2 off beers; $3 off craft cocktails", food:"$14 pizzas; 50% off select apps", tags:["brewery","food","groups"], source:"https://www.mbcrestaurants.com/kailua/", slots:{1:[[15.5,17.5]],2:[[15.5,17.5]],3:[[15.5,17.5]],4:[[15.5,17.5]],5:[[15.5,17.5]]}},
  {name:"The Boardroom Kailua", neighborhood:"Windward", area:"Kailua", days:"Wed–Sun", early:"5:00–6:00 PM", late:"9:00–11:30 PM Fri–Sat", beer:null, drinks:"$15 signatures; $8 oyster shooters", food:"$5 off select apps", tags:["cocktails","date","late"], source:"https://www.theboardroomkailua.com/", slots:{3:[[17,18]],4:[[17,18]],5:[[17,18],[21,23.5]],6:[[17,18],[21,23.5]],0:[[17,18]]}},
  {name:"The Garden Kailua", neighborhood:"Windward", area:"Kailua", days:"Mon–Fri", early:"3:00–6:00 PM", late:"—", beer:null, drinks:"Pau Hana beer, wine & cocktail specials", food:"Daily pizza specials", tags:["outdoor","music","food"], source:"https://www.thegardenkailua.com/", slots:{1:[[15,18]],2:[[15,18]],3:[[15,18]],4:[[15,18]],5:[[15,18]]}},
  {name:"Gyu-Kaku Windward Mall", neighborhood:"Windward", area:"Kāneʻohe", days:"Daily", early:"Mon/Thu all day; others 11 AM–6 PM", late:"Late window most days", beer:null, drinks:"Happy-hour drink pricing", food:"Happy-hour yakiniku pricing", tags:["food","late","groups"], source:"https://www.gyu-kaku.com/windward-mall/", slots:{0:[[11,18],[20,20.25]],1:[[11,20.25]],2:[[11,18],[20,20.25]],3:[[11,18],[20,20.25]],4:[[11,20.25]],5:[[11,18],[20,20.75]],6:[[11,18],[20,20.75]]}},
  {name:"BREW'd Craft Pub", neighborhood:"East Honolulu", area:"Kaimukī", days:"Daily", early:"4:00–6:00 PM", late:"—", beer:null, drinks:"$2 off full drafts; $6 wells & house wine", food:"$3 off appetizers & pub fare", tags:["brewery","food","dogs"], source:"https://www.brewdcraftpub.com/", slots:{0:[[16,18]],1:[[16,18]],2:[[16,18]],3:[[16,18]],4:[[16,18]],5:[[16,18]],6:[[16,18]]}},
  {name:"et al.", neighborhood:"East Honolulu", area:"Kāhala", days:"Daily", early:"Happy hour — verify current time", late:"—", beer:null, drinks:"Pau hana cocktail specials", food:"Sliders, arancini & snackable specials", tags:["upscale","date","food"], source:"https://etalhawaii.com/", slots:{}},
  {name:"Restaurant 604", neighborhood:"Central", area:"Pearl Harbor", days:"Mon–Fri", early:"3:00–5:00 PM", late:"—", beer:null, drinks:"Aloha Hour cocktails & drink specials", food:"Appetizer specials", tags:["waterfront","music","food"], source:"https://jbphh.greatlifehawaii.com/dining-retail/restaurants/restaurant-604", slots:{1:[[15,17]],2:[[15,17]],3:[[15,17]],4:[[15,17]],5:[[15,17]]}},
  {name:"Dixie Grill BBQ & Crab Shack", neighborhood:"Central", area:"Aiea", days:"Daily", early:"3:00–6:00 PM; Mon all day", late:"—", beer:9, drinks:"32oz draft $9; wells $7; Jameson/Jack $6", food:"$7 onion rings; $11 calamari; HH bites", tags:["bbq","sports","food"], source:"https://dixiegrill.com/aiea-near-aloha-stadium-dixie-grill-bbq-and-crab-shack-happy-hours-specials", slots:{0:[[15,18]],1:[[11,21]],2:[[15,18]],3:[[15,18]],4:[[15,18]],5:[[15,18]],6:[[15,18]]}},
  {name:"Little Joe's Steakhouse Pearl City", neighborhood:"Central", area:"Pearl City", days:"Nightly", early:"4:30–7:00 PM", late:"—", beer:4.95, drinks:"Beers from $4.95; wine from $8.95", food:"Discounted steakhouse menu until 6:30", tags:["steak","food","date","cheap"], source:"https://www.littlejoessteakhouse.com/happyhour", slots:{0:[[16.5,19]],1:[[16.5,19]],2:[[16.5,19]],3:[[16.5,19]],4:[[16.5,19]],5:[[16.5,19]],6:[[16.5,19]]}},
  {name:"Uncle Bo's Haleiwa", neighborhood:"North Shore", area:"Haleʻiwa", days:"Daily when open", early:"2:00–6:00 PM", late:"—", beer:null, drinks:"Happy-hour drink specials", food:"Happy-hour pupu menu", tags:["northshore","food","local"], source:"https://www.unclebosrestaurant.com/wp-content/uploads/2022/07/HALEIWA-DINNER-MENU-2.pdf", slots:{2:[[14,18]],3:[[14,18]],4:[[14,18]],5:[[14,18]],6:[[14,18]],0:[[14,18]]}},
];

const regions = [
  {key:"North Shore",label:"North Shore / Haleʻiwa",lat:21.593,long:-158.104,zoom:12},
  {key:"Windward",label:"Kailua / Kāneʻohe",lat:21.407,long:-157.744,zoom:12},
  {key:"Central",label:"Aiea / Pearl City",lat:21.397,long:-157.965,zoom:12},
  {key:"West Oahu",label:"Kapolei / Ko Olina",lat:21.338,long:-158.123,zoom:12},
  {key:"East Honolulu",label:"Kaimukī / Kāhala",lat:21.278,long:-157.789,zoom:13},
  {key:"Ala Moana",label:"Ala Moana",lat:21.291,long:-157.843,zoom:14},
  {key:"Kakaako",label:"Kakaʻako",lat:21.297,long:-157.858,zoom:14},
  {key:"Waikiki",label:"Waikīkī",lat:21.279,long:-157.829,zoom:14}
];

const state={q:"",neighborhood:"all",open:false,price:"any",time:"any",sort:"recommended",view:"map"};
const byId=id=>document.getElementById(id);
const grid=byId('venueGrid'), fullGrid=byId('venueGridFull'), resultCount=byId('resultCount');

function honoluluNow(){
  const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Pacific/Honolulu',weekday:'short',hour:'numeric',minute:'2-digit',hour12:false}).formatToParts(new Date());
  const map=Object.fromEntries(parts.map(p=>[p.type,p.value])); const days={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6}; let hour=Number(map.hour);if(hour===24)hour=0;
  return {day:days[map.weekday],hour:hour+Number(map.minute)/60,label:`${String(hour).padStart(2,'0')}:${map.minute}`};
}
function statusFor(v){const n=honoluluNow(),slots=v.slots[n.day]||[];for(const[s,e]of slots){if(n.hour>=s&&n.hour<e)return{key:'open',label:'Open now'}}const future=slots.find(([s])=>s>n.hour);if(future){let h=Math.floor(future[0]),m=future[0]%1?30:0;return{key:'later',label:`Starts ${h>12?h-12:h}:${m?'30':'00'} ${h>=12?'PM':'AM'}`}}return{key:'closed',label:slots.length?'Done today':'Check hours'}}
function isLate(v){return v.tags.includes('late')||v.late!=='—'}
function filtered(){let list=venues.filter(v=>{const text=(v.name+' '+v.area+' '+v.drinks+' '+v.food+' '+v.tags.join(' ')).toLowerCase();if(state.q&&!text.includes(state.q.toLowerCase()))return false;if(state.neighborhood!=='all'&&v.neighborhood!==state.neighborhood)return false;if((state.open||state.time==='open')&&statusFor(v).key!=='open')return false;if(state.time==='late'&&!isLate(v))return false;if(state.price!=='any'&&!(v.beer&&v.beer<=Number(state.price)))return false;return true});if(state.sort==='beer')list.sort((a,b)=>(a.beer??99)-(b.beer??99));if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(state.sort==='recommended')list.sort((a,b)=>{const sa=statusFor(a).key==='open'?0:1,sb=statusFor(b).key==='open'?0:1;return sa-sb||(a.beer??99)-(b.beer??99)});return list}
function initials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0]).join('').toUpperCase()}
function shortDeal(v){const parts=[];if(v.beer)parts.push(`<b>$${v.beer} beer</b>`);if(v.drinks&&v.drinks!=='—')parts.push(`<span>${v.drinks}</span>`);if(v.food&&v.food!=='—')parts.push(`<span>${v.food}</span>`);return parts.slice(0,2).join('')||'<span>See venue for current deal</span>'}
function cardHTML(v,full=false){const s=statusFor(v);return `<article class="venue-row"><div class="venue-main"><div class="venue-avatar">${initials(v.name)}</div><div><h3>${v.name}</h3><p>${v.days}</p></div></div><div class="venue-cell"><span class="mobile-label">Area</span><strong>${v.area}</strong></div><div class="venue-cell"><span class="mobile-label">Happy hour</span><strong>${v.early}</strong>${v.late!=='—'?`<small>${v.late}</small>`:''}</div>${full?`<div class="venue-cell"><span class="mobile-label">Drink deal</span>${v.drinks}</div><div class="venue-cell"><span class="mobile-label">Food deal</span>${v.food}</div>`:`<div class="venue-cell deal-stack"><span class="mobile-label">Deals</span>${shortDeal(v)}</div>`}<div class="venue-status"><span class="mobile-label">Status</span><span class="status ${s.key}">${s.label}</span></div><div class="venue-link"><a class="source-link" href="${v.source}" target="_blank" rel="noopener" aria-label="Verify ${v.name}">›</a></div></article>`}
function render(){const list=filtered();resultCount.textContent=list.length;grid.innerHTML=list.length?list.map(v=>cardHTML(v,false)).join(''):'<div style="padding:30px">No matching happy hours.</div>';fullGrid.innerHTML=list.length?list.map(v=>cardHTML(v,true)).join(''):'<div style="padding:30px">No matching happy hours.</div>';byId('localClock').textContent=honoluluNow().label}
function sync(){byId('neighborhoodFilter').value=state.neighborhood;byId('timeFilter').value=state.time;byId('priceFilter').value=state.price;byId('openNowFilter').checked=state.open;byId('sortSelect').value=state.sort;byId('searchInput').value=state.q;byId('headerSearch').value=state.q}
function clearFilters(){Object.assign(state,{q:"",neighborhood:"all",open:false,price:"any",time:"any",sort:"recommended"});sync();render();renderCoverage();if(hhMap)byId('recenterMap').click()}
function setView(mode){state.view=mode;byId('mapViewBtn').classList.toggle('active',mode==='map');byId('listViewBtn').classList.toggle('active',mode==='list');byId('mapMode').classList.toggle('hidden',mode!=='map');byId('listMode').classList.toggle('hidden',mode!=='list');if(mode==='map'&&hhMap)setTimeout(()=>hhMap.invalidateSize(),80)}

let hhMap, satelliteLayer;
function initMap(){
  if(!window.L || hhMap) return;
  hhMap=L.map('map',{zoomControl:true,scrollWheelZoom:true,attributionControl:true});
  const bounds=L.latLngBounds([[21.242,-158.305],[21.725,-157.615]]);
  satelliteLayer=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'}).addTo(hhMap);
  hhMap.fitBounds(bounds,{padding:[18,18]});
  regions.forEach(r=>{
    const count=venues.filter(v=>v.neighborhood===r.key).length;
    const icon=L.divIcon({className:'region-marker',html:`<div class="region-pin" data-region="${r.key}"><i>●</i><span>${r.label}<small>${count} spot${count===1?'':'s'}</small></span></div>`,iconSize:null,iconAnchor:[15,15]});
    const m=L.marker([r.lat,r.long],{icon}).addTo(hhMap);
    m.on('click',()=>{state.neighborhood=r.key;sync();render();renderCoverage();});
  });
  byId('recenterMap')?.addEventListener('click',()=>hhMap.fitBounds(bounds,{padding:[18,18]}));
  setTimeout(()=>hhMap.invalidateSize(),150);
  window.addEventListener('resize',()=>setTimeout(()=>hhMap.invalidateSize(),100));
}
function syncRegionMarkers(){ if(hhMap) setTimeout(()=>hhMap.invalidateSize(),80); }
function renderCoverage(){const strip=byId('coverageStrip');strip.innerHTML=regions.map(r=>{const count=venues.filter(v=>v.neighborhood===r.key).length;const active=state.neighborhood===r.key?' active':'';return `<button class="coverage-chip${active}" data-region="${r.key}">${r.label} · ${count}</button>`}).join('');strip.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{state.neighborhood=b.dataset.region;sync();render();renderCoverage();const r=regions.find(x=>x.key===b.dataset.region);if(hhMap&&r)hhMap.flyTo([r.lat,r.long],r.zoom,{duration:.7})}))}

['searchInput','headerSearch'].forEach(id=>byId(id).addEventListener('input',e=>{state.q=e.target.value;sync();render()}));
byId('neighborhoodFilter').addEventListener('change',e=>{state.neighborhood=e.target.value;render();renderCoverage();const r=regions.find(x=>x.key===state.neighborhood);if(hhMap&&r)hhMap.flyTo([r.lat,r.long],r.zoom,{duration:.7})});
byId('timeFilter').addEventListener('change',e=>{state.time=e.target.value;render()});byId('priceFilter').addEventListener('change',e=>{state.price=e.target.value;render()});byId('openNowFilter').addEventListener('change',e=>{state.open=e.target.checked;render()});byId('sortSelect').addEventListener('change',e=>{state.sort=e.target.value;render()});
byId('mapViewBtn').onclick=()=>setView('map');byId('listViewBtn').onclick=()=>setView('list');byId('navMap').onclick=()=>setView('map');byId('navList').onclick=()=>setView('list');byId('clearFilters').onclick=clearFilters;byId('clearFilters2').onclick=clearFilters;
const modal=byId('cityModal');byId('cityPill').onclick=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')};byId('modalClose').onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};modal.querySelector('.modal-backdrop').onclick=byId('modalClose').onclick;
renderCoverage();sync();render();initMap();setInterval(()=>{byId('localClock').textContent=honoluluNow().label;render()},60000);
