-- One-time setup for the HappyHr.Me community correction / new-venue form.
-- Public visitors may INSERT submissions but cannot read, edit, or delete them.

create table if not exists public.happy_hour_submissions (
  id bigint generated by default as identity primary key,
  submission_type text not null check (submission_type in ('correction','new_venue','contact')),
  venue_name text not null,
  market text not null,
  area text,
  address text,
  details text not null,
  source_url text,
  submitter_contact text,
  admin_notes text,
  status text not null default 'pending' check (status in ('pending','reviewed','applied','rejected')),
  created_at timestamptz not null default now()
);

alter table public.happy_hour_submissions enable row level security;

drop policy if exists "allow public happy hour submissions" on public.happy_hour_submissions;
create policy "allow public happy hour submissions"
on public.happy_hour_submissions
for insert
to anon, authenticated
with check (
  status = 'pending'
  and char_length(venue_name) between 1 and 200
  and char_length(market) between 1 and 120
  and submission_type in ('correction','new_venue','contact')
  and char_length(details) between 5 and 5000
);

grant insert on public.happy_hour_submissions to anon, authenticated;
grant usage, select on sequence public.happy_hour_submissions_id_seq to anon, authenticated;
